runtime: python310  # or python311 depending on your setup
entrypoint: gunicorn DrBartellWebsite.wsgi

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "DrBartellWebsite.settings"